title: OSM Bike Berlin Tagging Guide
email:
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: osmberlin
github_username: tordans

# Build settings
# theme: minima
plugins:
  - jekyll-feed
